### ISSUE TITLE
The API document page for Filter does not exist

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-bigtable#296] opened 2018-09-04 17:46 UTC
The Filter documentation doesn't exist at [https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/Filter](https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/Filter).

In addition, Filter is not listed as a class on the main doc page at [https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/](https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/).

**Comment by sduskis** [comment] 2018-10-08 15:37
This is a duplicate of #118

**Closed by sduskis** 2018-10-08 15:37 UTC
Labels: duplicate, type: docs
