### ISSUE TITLE
`DEADLINE_EXCEEDED` Error when using `table.dropRows()`

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-bigtable#79] opened 2018-04-05 20:45 UTC
When using the`table.dropRows()` method to clear a table, I receive the following error:
```
{ Error: 4 DEADLINE_EXCEEDED: Insufficient deadline for DropRowRange. Please try again with a longer request deadline.
    at new createStatusError (/temp-bt/node_modules/google-gax/node_modules/grpc/src/client.js:64:15)
    at /temp-bt/node_modules/google-gax/node_modules/grpc/src/client.js:583:15
  code: 4,
  metadata:
   Metadata {
     _internal_repr:
      { 'google.rpc.debuginfo-bin': [Array],
        'grpc-status-details-bin': [Array] } },
  details: 'Insufficient deadline for DropRowRange. Please try again with a longer request deadline.'
```
The associated code is:
```js
const Bigtable = require('@google-cloud/bigtable');

const bigtable = new Bigtable({
  projectId: 'some-project-id'
});

const INSTANCE_NAME = 'some-instance';

async function main() {
  await bigtable.createInstance(INSTANCE_NAME, {
    clusters: [{
      name: 'some-cluster',
      location: 'us-central1-c',
      nodes: 3
    }]
  });
  const instance = bigtable.instance(INSTANCE_NAME);
  const table = instance.table('someTable');
  await table.create({
    families: ['someFamily']
  });
  await table.insert({
    key: 'some-key',
    data: {
      someFamily: {
        someData: 'some-data'
      }
    }
  });
  await table.deleteRows(); // error thrown
}

main().catch(console.error);
```

**Comment by stephenplusplus** [comment] 2018-04-06 15:59
Confirmed. Here's what I know:

- We're calling directly through to GAPIC
- The error comes back immediately
- The [config file](https://github.com/googleapis/nodejs-bigtable/blob/f1e3ece3d7a6f4b93e6d3540700eb0d1f09852bd/src/v2/bigtable_table_admin_client_config.json#L54) specifies a `timeout_millis` of 60000
- Setting a [`deadline`](https://googleapis.github.io/gax-nodejs/global.html#CallOptions) value doesn't seem to have any effect

@alexander-fenster which direction should we go to try to solve this one?

**Comment by alexander-fenster** [comment] 2018-04-06 18:39
@igorbernstein2 can you point us to the right direction? `table.deleteRows()` calls `DropRowRange` message which does not list any way of setting any kind of deadline - or am I reading it wrong?

**Comment by sduskis** [comment] 2018-04-12 20:40
@stephenplusplus, the DropRowRange rpc will take quite a bit of time to execute this request.  1 minute is not a long enough span in some cases.  [Here's the yaml](https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/bigtableadmin_gapic.yaml#L573).

I'll raise a bug for this internally.  We ought to review all of our timeouts for Admin operations.  Once that happens, we'll need to regenerate the GAPIC code across the board.

**Comment by stephenplusplus** [comment] 2018-04-12 22:31
Ah, ok. So we're sending the right request, but the API is blocking it?

**Comment by sduskis** [comment] 2018-04-13 11:45
@stephenplusplus: correct.  The server side has a 2 minute minimum deadline, and the client sends 1 minute.

I'll take this bug for now.

**Comment by sduskis** [comment] 2018-04-23 20:59
@stephenplusplus, the file is generated, so we should probably fix the underlying configuration and regenerate node.js GAPIC.  @igorbernstein is going to work on the configuration part tomorrow.  We'll need help from @alexander-fenster after that.

I'm ok with changing the file manually, if you think that's ok.  If you're going to change it manually, I would suggest using at least 10 minutes.  We got guidance from the API owner that "no deadline" would be ideal.  @igorbernstein actually suggest 1 hour, if we need to hard-code something.

**Comment by alexander-fenster** [comment] 2018-04-23 21:03
Just FYI, it's now @crwilcox who will regenerate GAPIC (but I'll be happy to help if needed).

**Comment by pkriete** [comment] 2018-04-24 17:44
We're also seeing this (our call is `table.deleteRows({ prefix: '...' });`). It rejects almost immediately, definitely does not hit the 60s timeout alluded to above. The prefix in question matches a single row.

**Comment by sduskis** [comment] 2018-05-01 17:55
@crwilcox: We updated our internal configuration, so can you please regenerate GAPIC?

**Comment by sduskis** [comment] 2018-05-03 21:59
@stephenplusplusm can you please see if the system tests run now that #120 is merged?

**Comment by kolodny** [comment] 2018-05-04 15:43
It works for me now. I opened #123 to reenable the test

**Closed** 2018-05-07 14:07 UTC
Labels: priority: p2, type: bug
