### ISSUE TITLE
row.get() merges in stale columns

### ISSUE THREAD

**Issue by kolodny** [googleapis/nodejs-bigtable#151] opened 2018-05-27 14:48 UTC
nodejs-bigtable `v13.1`

When rehydrating a row, the deleted columns will still show up since we merge the old object with the new object

https://github.com/googleapis/nodejs-bigtable/blob/44a117212428587bf586e0c11e716182d871dec8/src/row.js#L733

Steps to repro

```js
// Insert row with two cells.
const ROW_KEY = 'mykey';
const rowToInsert = {
  key: ROW_KEY,
  data: {
    tcolumn: {
      tcell: 'myvalue',
    },
    col2: {
      foo: 'bar',
    },
  },
};
await table.insert(rowToInsert);
const [row] = await table.row(ROW_KEY).get();
// assert(row.data.tcolumn.tcell)

await row.deleteCells(['tcolumn:tcell']);
const [updatedRow] = await row.get();
// assert(row.data.tcolumn.tcell) // This should be false

// Do note that fetching a newly created row works since we don't merge in a stale row:

{
  await row.deleteCells(['tcolumn:tcell']);
  const [updatedRow] = await table.row(ROW_KEY).get();
  // assert(! row.data.tcolumn.tcell) // does not exists which is the expected result
}
```

**Comment by sduskis** [comment] 2018-06-01 20:53
This is a duplicate of #149.  My vote is to remove `row.data` to eliminate this problem and push users towards "doing the right thing".

**Closed** 2018-06-28 16:50 UTC
Labels: Breaking Change, cla: yes, priority: p1, status: investigating, type: bug
