### ISSUE TITLE
createReadStream issue against Bigtable Emulator

### ISSUE THREAD

**Issue by fabifink** [googleapis/nodejs-bigtable#779] opened 2020-07-31 11:37 UTC
Hello,

I am experiencing a problem regarding the `@google-cloud/bigtable` library when executed against the Bigtable Emulator. In version 1.x of this library, I was able to use the gcloud cli Bigtable Emulator as well as a Bigtable Cluster hosted on GCP. Unfortunately, when we switched to v2.x, the library did not behave as expected, when used with the Bigtable Emulator. This forces us to run all our integration tests against a real GCP Bigtable Instance, which is very inconvenient.

This issue still persists in the latest library version.

I could track down the issue to the `createReadStream()`, `row.get()` and `row.exists()` functionality. All of those functions do not resolve when they are called for non existing rows.

#### Environment details

  - OS: MacOs
  - Node.js version: 14.3.0
  - npm version: 6.14.7
  - `@google-cloud/bigtable` version: 3.0.1

#### Steps to reproduce

To reproduce the issue I have created a small [repository](https://github.com/fabifink/bigtable-test) with some very basic tests that reproduce these issues.

Within the [readme](https://github.com/fabifink/bigtable-test/blob/master/README.md) I have described how to run the tests against the Emulator as well as against GCP. When the tests are executed against a GCP Bigtable instance, everything is fine, but the emulator hangs until timeout.

Thanks in advance for your support!

**Comment by stephenplusplus** [comment] 2020-07-31 17:05
Thank you very much for the detailed report! This appears to be a duplicate of #612 -- would you mind adding your report as part of the thread there?

**Closed by stephenplusplus** 2020-07-31 17:05 UTC
Labels: api: bigtable
