### ISSUE TITLE
Try to delete cells of a column family but don't work

### ISSUE THREAD

**Issue by Devi7005** [googleapis/nodejs-bigtable#149] opened 2018-05-24 17:45 UTC
In my column family "tcolumn", I have these data for a row and I want to delete cell "tcell": 
```
{
 tcolumn: {
   tcell: [ {
    value: "myvalue",
    labels: [],
    timestamp: "thetimestamp"
  } ]
 }
}
```
I try to do row.deleteCells(["tcolumn:tcell"]) but I still see my cell "tcell" in the data

#### Environment details
  - Node.js version: 8.9.4
  - npm version:
  - `@google-cloud/bigtable` version: 0.13.1

Thanks!

**Comment by kolodny** [comment] 2018-05-27 15:03
Hi @Devi7005 and thanks for the bug report. It looks like we have a bug where we merge in stale columns when calling `get()` on rows after they contain columns that shouldn't exists. I suspect that's whats happening in your use case. If it is, as a workaround until that issue is resolved I would suggest recreating the row object, and then calling `get()` on the new object. See below for a demonstration of what I mean:

```js
const [unhydratedRow] = table.row('my-key');
const firstRowWithTColumn = await unhydratedRow.get(); // note that unhydratedRow === firstRowWithTColumn
await firstRowWithTColumn.deleteCells(['tcolumn:tcell']);
// firstRowWithTColumn.data.tcolumn still exists, it may make sense to update the object at this point
const [secondRowWithTColumn] = firstRowWithTColumn.get() // // note that unhydratedRow === firstRowWithTColumn && firstRowWithTColumn === secondRowWithTColumn
// secondRowWithTColumn.data.tcolumn still exists since we just extended the original object

// This is what you want to do instead:
const [newUnhydratedRow] = table.row('my-key');
const [thirdRowWithoutTColumn] = await newUnhydratedRow.get();
thirdRowWithoutTColumn.data.tcolumn // does not exists
```

I opened #151 to track the issue of merging in stale columns.

Let me know if this is the cause of the bug you're experiencing.

Thanks!

**Comment by Devi7005** [comment] 2018-05-28 12:32
Ok, I solve the problem by getting a row directly from table by his key like
`const [row] = table.row('my-key');
 await row.deleteCells(['tcolumn:tcell']);
`

But when I get a row from reader stream, deleting don't work:
`readerstream.on('data', row => {
   row.deleteCells(['tcolumn:tcell']); //don't work
 });
`

**Comment by sduskis** [comment] 2018-06-01 20:52
I'm going to suggest hat we remove `row.data`.  It's a backwards incompatible change, but I think that it's important to do before we hit beta.  We'll definitely need to document this change in our release notes

**Comment by sduskis** [comment] 2018-06-01 20:54
I'm going to close this in favor of #151.  I think that these are duplicates.  Please reopen if I misunderstood the nature of the problem.

**Closed by sduskis** 2018-06-01 20:54 UTC
Labels: Breaking Change, cla: yes, priority: p1, type: bug
