### ISSUE TITLE
The stream returned by createReadStream method didn't emit 'end' or any event if the table is empty or there is no data available for the query

### ISSUE THREAD

**Issue by cpt-corvus** [googleapis/nodejs-bigtable#612] opened 2020-02-04 14:47 UTC
Hello,

The stream returned by createReadStream method in bigtable nodejs client didn't emit 'end' or any event if there is no data in the table matches the used query.

Environment details
OS: Ubuntu 19.10
Node.js version: 10.15.2
npm version: 6.12.0
@google-cloud/bigtable version: 2.3.1
I also use bigtable emulator

Steps to reproduce
1. Use createReadStream to create stream for a query that the table didn't have data for.
2. Try to listen of 'end' & 'data' events in the returned stream

Thanks!

**Comment by stephenplusplus** [comment] 2020-02-20 15:35
Both #555 and this issue use the Bigtable emulator, which is the only environment for this condition. I have successfully reproduced, and the biggest problem is that there is not a "response" event when using the emulator. The underlying library we use to handle automatically retrying failed requests, `retry-request`, relies on that initial response event to determine how to proceed-- should it retry or not (200? 500? etc)

I've done some digging, and there are a couple things that need to be addressed:

1) Bigtable uses retry-request directly-- but it uses it with a stream from `google-gax` that *also* uses retry-request. That effectively means we can get rid of retry-request from this library, and leave it in google-gax. **But!** Bigtable sets some special retry-request options, and google-gax doesn't have an open door to pass those through to retry-request. So, that would be the first step: allow retry-request options from google-gax.

2) Then, we have to figure out how to get a "metadata" or "response" event from the emulator when it has no results. In its absence, we would probably need to do something creative from either this library or retry-request.

I've opened https://github.com/googleapis/gax-nodejs/issues/726 to address #&shy;1.

**Comment by lkj19zpdiDDe** [comment] 2020-06-29 19:36
Any guess on the resolution time-frame? I'm also experiencing this issue.

**Comment by fabifink** [comment] 2020-09-14 07:06
I am experiencing the same problem when executing against the Bigtable Emulator. In version 1.x of this library, I was able to use the gcloud cli Bigtable Emulator as well as a Bigtable Cluster hosted on GCP. Unfortunately, when we switched to v2.x, the library did not behave as expected, when used with the Bigtable Emulator. This forces us to run all our integration tests against a real GCP Bigtable Instance, which is very inconvenient.

This issue still persists in the latest library version.

I could track down the issue to the not only `createReadStream()`, but also `row.get()` and `row.exists()` functionality. All of those functions do not resolve when they are called for non existing rows.

#### Environment details

  - OS: MacOs
  - Node.js version: 14.3.0
  - npm version: 6.14.7
  - `@google-cloud/bigtable` version: 3.0.1

#### Steps to reproduce

To reproduce the issue I have created a small [repository](https://github.com/fabifink/bigtable-test) with some very basic tests that reproduce these issues.

Within the [readme](https://github.com/fabifink/bigtable-test/blob/master/README.md) I have described how to run the tests against the Emulator as well as against GCP. When the tests are executed against a GCP Bigtable instance, everything is fine, but the emulator hangs until timeout.

Do you have any indication on when you are able to resolve this issue? Thanks in advance for your support!

**Comment by fabifink** [comment] 2020-10-05 09:10
@stephenplusplus The PR for [googleapis/gax-nodejs#726](https://github.com/googleapis/gax-nodejs/issues/726) seems to be merged. Can you go ahead with this issue now?

**Comment by gregsherrid** [comment] 2021-01-03 22:57
@stephenplusplus I'm also seeing this issue, and I'm curious if there's a timeline on resolving this?

**Comment by ansf** [comment] 2021-01-29 16:45
Can confirm that `createReadStream()` and `getRows()` hang when the table is empty on the emulator.

Unfortunately the workaround does not work for me.

Any news on this issue?
I think it should be labeled as bug instead of question.

**Comment by ansf** [comment] 2021-02-01 08:01
Ok, so I managed to get the workaround working.

I tried this code (which the types suggested):

```
new Bigtable({ BigtableClient: { grpc: grpc, sslCreds: grpc.credentials.createInsecure() }})
```


But I actually had to use this exact code from stackoverflow:

```
new Bigtable({ grpc, sslCreds: grpc.credentials.createInsecure() }
```

**Comment by danieljbruce** [comment] 2022-04-04 18:29
It seems this issue is no longer present as of version 3.0.0-beta.0 of nodejs-bigtable. Try upgrading your client library to see if that solves the issue.

**Closed** 2022-04-07 19:39 UTC
Labels: type: question, api: bigtable
