### ISSUE TITLE
v0.13 readStream don't fetch all rows

### ISSUE THREAD

**Issue by Turniii** [googleapis/nodejs-bigtable#148] opened 2018-05-23 16:53 UTC
Hello, 

I have an issue with the read stream function.
I have used the cbt util to count the number of rows contained by a table. The result is 888,902 rows.
Now when I am trying to get the same result with node (google-cloud/bigtable@0.13.1), I get a different result, which is 629,444 rows.
I am using the following code: 
```
const Bigtable = require('@google-cloud/bigtable');

const bigtable = Bigtable({
  projectId: '**'
});

let count = 0;
const instance = bigtable.instance('**');

instance.table('table').createReadStream()
  .on('data', () => {
    count++;
  })
  .on('end', () => console.log('end, count:', count));
```
After struggling a bit I decided to try an older version (10.2) for a result of 889,240 which is the same as the cbt utils (with some rows added during the process) .
I tried with several version, getting the below results : 
10.2: 889,240
11.1: 889,240
12.1: 889,240
13.0: 604,802
13.1: 629,444

We can see that from the version 0.13 the number of rows drop significantly.

**Comment by kolodny** [comment] 2018-05-25 16:11
Hi @Turniii thanks for reporting this bug.

I'm trying to reproduce this bug but I can't seem to get the same result you got. Below is the file I'm using. Let me know what I can change to get the same results you're experiencing, Thanks!

```js
/* eslint-disable no-console, no-debugger */

const bigtable = require('@google-cloud/bigtable');

const INSTANCE_ID = 'mkolodny-nodejs-repros';
const TABLE_NAME = 'github-issue-148';
const COLUMN_FAMILY_NAME = 'cf1';
const TOTAL_ROWS = 1000000;

const forceRegenerate = false;

(async () => {
  try {
    const bigtableClient = bigtable();
    const instance = bigtableClient.instance(INSTANCE_ID);
    const table = instance.table(TABLE_NAME);

    // Ensure table exists.
    const [tableExists] = await table.exists();
    console.log(`table ${TABLE_NAME} exists: ${tableExists}`);

    if (forceRegenerate && tableExists) {
      console.log(`force deleting table ${TABLE_NAME}`);
      await table.delete();
    }

    if (!tableExists) {
      console.log(`Creating table ${TABLE_NAME}`);
      const options = {
        families: [COLUMN_FAMILY_NAME],
      };
      await table.create(options);

      // Insert data.
      console.log('inserting rows');
      const rowsToInsert = [];
      let i = 0;
      while (i < TOTAL_ROWS) {
        for (let j = 0; j < 10000; j++, i++) {
          rowsToInsert.push({
            key: `row-${i}`,
            data: {
              [COLUMN_FAMILY_NAME]: {
                column: `cell value for #${i}`,
              },
            },
          });
        }
        await table.insert(rowsToInsert);
        console.log(`inserted up to ${i}`);
        rowsToInsert.length = 0;
      }
    }

    let count = 0;
    table
      .createReadStream()
      .on('data', () => {
        count++;
      })
      .on('end', () => console.log(`end, count: ${count}`));

    console.log('done');
  } catch (error) {
    console.error('Something went wrong:', error);
  }
})();
```

I always get `end, count: 1000000`

**Comment by sduskis** [comment] 2018-06-01 20:50
@Turniii: we cannot reproduce this issue.  Is there anything more information that might help us debug this?

**Comment by sduskis** [comment] 2018-06-01 20:51
@kolodny: let's review the retry logic one more time.

**Comment by sduskis** [comment] 2018-06-08 13:38
I don't think that there's anything active that we can do without a repro.  We tried a whole bunch of ways to reproduce this, but we couldn't.  @Turniii, I'm going to have to close this until we have a repro.

**Closed by sduskis** 2018-06-08 13:38 UTC
Labels: priority: p1, status: investigating, type: bug
